//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumparareItem
    {
        public int CumparareId { get; set; }
        public int ProdusId { get; set; }
        public Nullable<int> NumarIteme { get; set; }
    
        public virtual Cumparare Cumparare { get; set; }
        public virtual Produse Produse { get; set; }
    }
}
